### ISSUE TITLE
Add basic github workflow for automated testing

### ISSUE THREAD

**Issue by masadcv** [cai4cai/torchsparsegradutils#10]
To add github workflows for automated testing with unittests + formating etc

**Comment by tvercaut** [comment]
@theo-barfoot : As discussed earlier, feel free to make a PR to activate Github Actions.

I would suggest staring from the example here:
https://github.com/rbialon/flake8-annotations#example-usage

This would also address #8

**Comment by theo-barfoot** [comment]
I had now setup a basic github CI workflow on the main branch.

However, there are no GPU/CUDA based tests. I will look into setting this up and add the jax and cupy tests during automated testing.

@tvercaut Do I also need to run Black in my github workflow? Or is flake8 sufficient here?

**Comment by tvercaut** [comment]
Looks good to. It would be an overkill for such a repo to set up our own GPU-enabled CI runners.

flake8 is sufficient now.
