### ISSUE TITLE
Add conjugate gradient solver in pure python

### ISSUE THREAD

**Issue by tvercaut** [cai4cai/torchsparsegradutils#3]
There are no symmetric or generic sparse linear system solver currently in pytorch:
https://github.com/pytorch/pytorch/issues/69538

A first workaround for positive symmetric definite (PSD) matrices is to use the CG solver from cornellius-gp:
https://github.com/cornellius-gp/linear_operator/blob/main/linear_operator/utils/linear_cg.py

For simplicity, we could just copy paste their file (and unit test) to reduce the complexity of our dependencies

**Comment by tvercaut** [comment]
Closing now that CG is avalaible. Other options now tracked in #22 and #23

**Comment by josecuev** [comment]
@tvercaut can you please, tell me how can use CG to solve a sparse linear system? I was searching in the documentation but I did not found anything. Thanks in advance.

**Comment by tvercaut** [comment]
Please have a look at the unit tests for now. There is also a WIP notebook here:
https://github.com/cai4cai/torchsparsegradutils/blob/test-notebook/tests/spd_forward_solve_notebook.ipynb

**Comment by josecuev** [comment]
Thank you for your fast answer! I am cheking it now.
