### ISSUE TITLE
Limitation by INT_MAX elements

### ISSUE THREAD

**Issue by EvgenyUgolkov** [cai4cai/torchsparsegradutils#52]
Good day!

I am trying to use sparse.mm for my custom layer for the super-resolution problem, and seems that my tensors are a bit large. When I am implementing the sparse matrix multiplication of my sparse features to the dense weights like this

result = sparse_mm(**sparse_tensor_2d**, **self.weights**).to_sparse().coalesce() 

I get the 

RuntimeError: nonzero is not supported for tensors with more than INT_MAX elements,   file a support request

The size of my **sparse_tensor_2d** is (33554432 x 16), and the size of the dense **self.weights** tensor is (16, 64)

Could you tell me, can this problem be solved by changing the INT_MAX? If yes, how can I do it?

Regards, Evgeny

**Comment by tvercaut** [comment]
This is a known pytorch issue as far as I can tell: https://github.com/pytorch/pytorch/issues/51871

That said, our `sparse_mm` function is for sparse times dense matrix multiplication and thus results in a dense matrix. Your use case may be specific but in general, there is no obvious reason to call `to_sparse()` (which is where `nonzero` is probably being called) on the result of our `sparse_mm`.

-> Closing this

**Comment by EvgenyUgolkov** [comment]
> This is a known pytorch issue as far as I can tell: [pytorch/pytorch#51871](https://github.com/pytorch/pytorch/issues/51871)
> 
> That said, our `sparse_mm` function is for sparse times dense matrix multiplication and thus results in a dense matrix. Your use case may be specific but in general, there is no obvious reason to call `to_sparse()` (which is where `nonzero` is probably being called) on the result of our `sparse_mm`.
> 
> -> Closing this

Thank you!
