### ISSUE TITLE
RuntimeError: "addmm_sparse_cuda" not implemented for 'Half'

### ISSUE THREAD

**Issue by EvgenyUgolkov** [cai4cai/torchsparsegradutils#53]
Dear Team, good day! I try to run the sparse mm with the float16 tensors, and faced the following error:

RuntimeError: "addmm_sparse_cuda" not implemented for 'Half'

Could you tell me, do you know a potential solutions to it?

Regards, Evgeny

**Comment by tvercaut** [comment]
This is out of scope for this repo and likely a pytorch limitation. See e.g. https://github.com/pytorch/pytorch/issues/41069
-> closing this

**Comment by EvgenyUgolkov** [comment]
> This is out of scope for this repo and likely a pytorch limitation. See e.g. [pytorch/pytorch#41069](https://github.com/pytorch/pytorch/issues/41069) -> closing this

@tvercaut 

Thank you!
